msg91.settings:
  label: 'MSG91 SMS Settings'
  type: config_object
  mapping:
    msg91_authKey:
      type: string
      label: 'MSG91 Authentication Key'
    msg91_senderID:
      type: string
      label: 'MSG91 Sender ID'
    msg91_route:
      type: integer
      label: 'MSG91 SMS Route'
    msg91_country_code:
      type: integer
      label: 'MSG91 Country Code'
    msg91_auth_url:
      type: string
      label: 'MSG91 Auth URL'
